### ISSUE TITLE
How to make it build and run

### ISSUE THREAD

**Issue by trondulseth** [digitalocean/sample-nuxtjs#2]
Would be nice if the readme could include some information as how to set up the component in the admin:

![Skjermbilde 2020-12-11 kl  10 09 43](https://user-images.githubusercontent.com/5379940/101884474-097aa600-3b99-11eb-948f-2490971c12d2.png)

Trying to deploy as is, just keeps on spinning with no output:

![Skjermbilde 2020-12-11 kl  10 13 50](https://user-images.githubusercontent.com/5379940/101884857-99205480-3b99-11eb-8401-7f9521db773a.png)

**Comment by kamaln7** [comment]
Hi @trondulseth 

The app as configured in the screenshot looks fine. I think you're running into a one-off issue. You also shouldn't see an empty build log so there's definitely an issue there at least. Could you please open a support ticket so we can look into what's happening?
